### ISSUE TITLE
Using filter doesn't hide the menu entries of filtered out markers

### ISSUE THREAD

**Issue by cadon** [alex4401/mediawiki-extensions-DataMaps#133] opened 2023-03-19 23:20 UTC
**Describe the bug**
When filtering out markers, e.g. using `{{DataMap:Maps/Exploration/The Island|filter=explorer-note}}`, the entries of the other markers in the menu on the left are still shown, despite the markers are not shown on the map (as expected).

**To Reproduce**
See https://ark.wiki.gg/wiki/The_Island/Spawn_Locations for an example. On this map only the spawn locations are shown, but on the menu on the left all the available marker groups are listed.

**Expected behavior**
Only the menu entries of shown markers should have an entry on the left to toggle their visibility.

Maybe related to or duplicate of #131

**Comment by alex4401** [comment] 2023-03-20 03:53
Duplicate of #130, fixed in development branch and will be deployed when v0.16.0 is ready (may be one more week if I don't split the release into two parts).

**Closed by alex4401** 2023-03-20 03:53 UTC
Labels: 1. bug
